### ISSUE TITLE
Assertionerror when trying to import cards on linux

### ISSUE THREAD

**Issue by mewmew419** [mi-ael/genki_anki_deck_generator#23]
Import failed.
Traceback (most recent call last):
  File "/usr/share/anki/aqt/importing.py", line 339, in importFile
    importer.run()
  File "/usr/share/anki/anki/importing/apkg.py", line 39, in run
    Anki2Importer.run(self)
  File "/usr/share/anki/anki/importing/anki2.py", line 23, in run
    self._prepareFiles()
  File "/usr/share/anki/anki/importing/anki2.py", line 38, in _prepareFiles
    self.src = Collection(self.file)
  File "/usr/share/anki/anki/storage.py", line 20, in Collection
    assert path.endswith(".anki2")
AssertionError

anyway to fix this

**Comment by mi-ael** [comment]
Could you provide a bit more Information about your environment.

I could not reproduce your issue under archlinux using Anki 2.1.66. This post ( https://www.reddit.com/r/Anki/comments/obwweo/assertionerror_when_trying_to_import_deck/ ) suggests this might happen if you use a very old version of Anki.

**Comment by mewmew419** [comment]
Omg u were right sorry for the trouble it’s working now!

**Comment by mi-ael** [comment]
happy to help!
